#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    Swedish,
    English,
}

impl Default for Language {
    fn default() -> Self {
        Language::Swedish
    }
}

impl Language {
    pub fn toggle(self) -> Self {
        match self {
            Language::Swedish => Language::English,
            Language::English => Language::Swedish,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Language::Swedish => "Svenska",
            Language::English => "English",
        }
    }
}

#[allow(dead_code)]
pub struct LangPack {
    pub printer: &'static str,
    pub active: &'static str,
    pub done: &'static str,
    pub failed: &'static str,
    pub photos_count: &'static str,
    pub gallery: &'static str,
    pub no_photos: &'static str,
    pub preview: &'static str,
    pub settings: &'static str,
    pub paper_size: &'static str,
    pub copies: &'static str,
    pub add_to_queue: &'static str,
    pub print_queue: &'static str,
    pub rescan: &'static str,
    pub print_queue_bottom: &'static str,
    pub queue_empty: &'static str,
    pub job_status: &'static str,
    pub no_jobs: &'static str,
    pub clear_completed: &'static str,
    pub status_queued: &'static str,
    pub status_printing: &'static str,
    pub status_done: &'static str,
    pub status_failed: &'static str,
    pub toast_added: &'static str,
    pub toast_printed: &'static str,
    pub toast_rescanned: &'static str,
    pub copy_label: &'static str,
    pub copies_label: &'static str,
    pub printer_for_size: &'static str,
    pub no_printer_for_size: &'static str,
    // Source select screen
    pub source_select_title: &'static str,
    pub source_select_subtitle: &'static str,
    pub source_usb_camera: &'static str,
    pub source_bluetooth: &'static str,
    pub source_google_photos: &'static str,
    pub source_bluetooth_soon: &'static str,
    pub importing: &'static str,
    pub import_usb_scanning: &'static str,
    pub import_usb_done: &'static str,
    pub back_to_sources: &'static str,
    pub source_mobile: &'static str,
    pub mobile_upload_title: &'static str,
    pub mobile_upload_hint: &'static str,
    pub mobile_upload_url: &'static str,
    pub mobile_upload_refresh: &'static str,
    pub mobile_upload_done: &'static str,
    pub wifi_step_1: &'static str,
    pub wifi_step_2: &'static str,
    pub wifi_step_3: &'static str,
    pub wifi_open_settings: &'static str,
    pub google_drive_title: &'static str,
    pub google_drive_auth_hint: &'static str,
    pub google_drive_visit_url: &'static str,
    pub google_drive_enter_code: &'static str,
    pub google_drive_waiting: &'static str,
    pub google_drive_denied: &'static str,
    pub google_drive_expired: &'static str,
    pub google_drive_select_photos: &'static str,
    pub google_drive_download: &'static str,
    pub google_drive_downloaded: &'static str,
    pub google_drive_no_config: &'static str,
    pub google_photos_downloaded: &'static str,
    pub wired_usb_cable: &'static str,
    pub wired_no_phone: &'static str,
    pub wired_select_phone: &'static str,
    pub wired_select_photos: &'static str,
    pub wired_imported: &'static str,
    pub wired_import: &'static str,
    pub tab_drive: &'static str,
    pub tab_photos: &'static str,
    pub mobile_menu_title: &'static str,
    pub mobile_android: &'static str,
    pub mobile_iphone: &'static str,
    pub connect_phone_title: &'static str,
    pub connect_phone_android: &'static str,
    pub connect_phone_iphone: &'static str,
    pub connect_phone_hint: &'static str,
    pub connect_phone_search: &'static str,
    pub connect_phone_found: &'static str,
    pub connect_phone_scanning: &'static str,
    pub connect_phone_searching: &'static str,
    pub connect_phone_not_found: &'static str,
    pub phone_folders_title: &'static str,
    pub phone_folders_hint: &'static str,
    pub connect_phone_gvfs_hint: &'static str,
    pub print_done_title: &'static str,
    pub print_done_subtitle: &'static str,
    pub confirm_clear_queue: &'static str,
    pub wifi_qr_upload: &'static str,
    pub wifi_network_label: &'static str,
    pub wifi_password_label: &'static str,
    pub wifi_connect_then_scan: &'static str,
    pub wifi_step_connect: &'static str,
    pub wifi_step_upload: &'static str,
    pub mobile_cable_connect: &'static str,
    pub select_all: &'static str,
    pub deselect_all: &'static str,
}

pub const SWEDISH: LangPack = LangPack {
    printer: "Skrivare",
    active: "Aktiv",
    done: "Klar",
    failed: "Misslyckades",
    photos_count: "bilder",
    gallery: "Galleri",
    no_photos: "Inga bilder hittades.\nLägg bilder i fotomappen och tryck Skanna om.",
    preview: "Förhandsvisning",
    settings: "Inställningar",
    paper_size: "Pappersstorlek",
    copies: "Antal kopior",
    add_to_queue: "Lägg i kö",
    print_queue: "Skriv ut kö",
    rescan: "Skanna om",
    print_queue_bottom: "Utskriftskö",
    queue_empty: "Kön är tom — lägg till bilder från galleriet",
    job_status: "Jobbstatus",
    no_jobs: "Inga utskriftsjobb än",
    clear_completed: "Rensa färdiga",
    status_queued: "I kö",
    status_printing: "Skriver ut",
    status_done: "Klar",
    status_failed: "Misslyckades",
    toast_added: "tillagd i kön",
    toast_printed: "Skickade {} jobb till skrivaren",
    toast_rescanned: "Skannade om bildmappen",
    copy_label: "kopia",
    copies_label: "kopior",
    printer_for_size: "Skrivare",
    no_printer_for_size: "Ingen skrivare konfigurerad",
    source_select_title: "MITSUBISHI Photo Kiosk",
    source_select_subtitle: "Välj källa för dina bilder",
    source_usb_camera: "USB / KAMERA MINNE",
    source_bluetooth: "BLUETOOTH",
    source_google_photos: "GOOGLE FOTO",
    source_bluetooth_soon: "Bluetooth — kommer snart",
    importing: "Importerar...",
    import_usb_scanning: "Söker efter bilder på USB...",
    import_usb_done: "USB-import klar",
    back_to_sources: "← Tillbaka till källor",
    source_mobile: "MOBIL",
    mobile_upload_title: "Ladda upp från mobil",
    mobile_upload_hint: "Skanna QR-koden med din telefon och välj bilder",
    mobile_upload_url: "Eller besök",
    mobile_upload_refresh: "🔄 Uppdatera bilder",
    mobile_upload_done: "Klar",
    wifi_step_1: "1. Anslut till WiFi",
    wifi_step_2: "2. Skanna QR-koden",
    wifi_step_3: "3. Välj bilder att skriva ut",
    wifi_open_settings: "Öppna WiFi-inställningar på din telefon",
    google_drive_title: "Google Foto",
    google_drive_auth_hint: "Logga in på ditt Google-konto i webbläsaren",
    google_drive_visit_url: "Besök",
    google_drive_enter_code: "Ange kod",
    google_drive_waiting: "Väntar på auktorisering...",
    google_drive_denied: "Åtkomst nekad",
    google_drive_expired: "Tiden gick ut — försök igen",
    google_drive_select_photos: "Välj bilder att hämta",
    google_drive_download: "⬇ Hämta valda",
    google_drive_downloaded: "{} bilder hämtade från Google Foto",
    google_drive_no_config: "Google Foto är inte konfigurerat. Lägg till client_id och client_secret i config.toml.",
    google_photos_downloaded: "{} bilder hämtade från Google Foto",
    wired_usb_cable: "USB-KABEL",
    wired_no_phone: "Ingen telefon hittades via USB",
    wired_select_phone: "Välj telefon",
    wired_select_photos: "Välj bilder från telefon",
    wired_imported: "bilder importerade",
    wired_import: "⬇ Importera valda",
    tab_drive: "Drive",
    tab_photos: "Foto",
    mobile_menu_title: "Importera från mobil",
    mobile_android: "🤖 Android",
    mobile_iphone: "🍎 iPhone",
    connect_phone_title: "Anslut telefon",
    connect_phone_android: "Koppla in din Samsung Galaxy/Android med USB-kabel",
    connect_phone_iphone: "Koppla in din iPhone med USB-kabel",
    connect_phone_hint: "Lås upp telefonen och välj \"Filöverföring\" om den frågar",
    connect_phone_search: "🔄 Sök igen",
    connect_phone_found: "Telefon hittad! Öppnar bilder...",
    connect_phone_scanning: "Telefon hittad! Laddar bilder, var god vänta...",
    connect_phone_searching: "Söker efter telefon...",
    connect_phone_not_found: "Ingen telefon hittades. Kontrollera att USB-kabeln är ansluten och att telefonen är upplåst.",
    phone_folders_title: "Välj mapp",
    phone_folders_hint: "Tryck på en mapp för att se bilderna",
    connect_phone_gvfs_hint: "Tips: Installera gvfs-mtp om telefonen inte visas.",
    print_done_title: "Tack för din beställning!",
    print_done_subtitle: "Dina bilder skrivs ut. Ta med dig dem när de är klara.",
    confirm_clear_queue: "Bekräfta",
    wifi_qr_upload: "📶 WiFi / QR-kod",
    wifi_network_label: "Nätverk",
    wifi_password_label: "Lösenord",
    wifi_connect_then_scan: "1. Anslut till WiFi ovan\n2. Skanna QR-koden med kameran",
    wifi_step_connect: "1. Anslut till WiFi",
    wifi_step_upload: "2. Ladda upp bilder",
    mobile_cable_connect: "🔌 Anslut med kabel istället",
    select_all: "☑ Markera alla",
    deselect_all: "☐ Avmarkera alla",
};

pub const ENGLISH: LangPack = LangPack {
    printer: "Printer",
    active: "Active",
    done: "Done",
    failed: "Failed",
    photos_count: "photos",
    gallery: "Gallery",
    no_photos: "No photos found.\nPlace images in the photo directory and press Rescan.",
    preview: "Preview",
    settings: "Settings",
    paper_size: "Paper Size",
    copies: "Copies",
    add_to_queue: "Add to Queue",
    print_queue: "Print Queue",
    rescan: "Rescan",
    print_queue_bottom: "Print Queue",
    queue_empty: "Queue is empty — add photos from the gallery",
    job_status: "Job Status",
    no_jobs: "No print jobs yet",
    clear_completed: "Clear Completed",
    status_queued: "Queued",
    status_printing: "Printing",
    status_done: "Done",
    status_failed: "Failed",
    toast_added: "added to queue",
    toast_printed: "Sent {} job(s) to printer",
    toast_rescanned: "Rescanned photo directory",
    copy_label: "copy",
    copies_label: "copies",
    printer_for_size: "Printer",
    no_printer_for_size: "No printer configured",
    source_select_title: "MITSUBISHI Photo Kiosk",
    source_select_subtitle: "Choose your photo source",
    source_usb_camera: "USB / CAMERA MEMORY",
    source_bluetooth: "BLUETOOTH",
    source_google_photos: "GOOGLE PHOTOS",
    source_bluetooth_soon: "Bluetooth — coming soon",
    importing: "Importing...",
    import_usb_scanning: "Scanning USB for photos...",
    import_usb_done: "USB import complete",
    back_to_sources: "← Back to sources",
    source_mobile: "MOBILE",
    mobile_upload_title: "Upload from phone",
    mobile_upload_hint: "Scan the QR code with your phone and select photos",
    mobile_upload_url: "Or visit",
    mobile_upload_refresh: "🔄 Refresh photos",
    mobile_upload_done: "Done",
    wifi_step_1: "1. Connect to WiFi",
    wifi_step_2: "2. Scan the QR code",
    wifi_step_3: "3. Select photos to print",
    wifi_open_settings: "Open WiFi settings on your phone",
    google_drive_title: "Google Photos",
    google_drive_auth_hint: "Sign in to your Google account in the browser",
    google_drive_visit_url: "Visit",
    google_drive_enter_code: "Enter code",
    google_drive_waiting: "Waiting for authorization...",
    google_drive_denied: "Access denied",
    google_drive_expired: "Timed out — please try again",
    google_drive_select_photos: "Select photos to download",
    google_drive_download: "⬇ Download selected",
    google_drive_downloaded: "{} photos downloaded from Google Photos",
    google_drive_no_config: "Google Photos is not configured. Add client_id and client_secret to config.toml.",
    google_photos_downloaded: "{} photos downloaded from Google Photos",
    wired_usb_cable: "USB-CABLE",
    wired_no_phone: "No phone detected via USB",
    wired_select_phone: "Select phone",
    wired_select_photos: "Select photos from phone",
    wired_imported: "photos imported",
    wired_import: "⬇ Import selected",
    tab_drive: "Drive",
    tab_photos: "Photos",
    mobile_menu_title: "Import from phone",
    mobile_android: "🤖 Android",
    mobile_iphone: "🍎 iPhone",
    connect_phone_title: "Connect phone",
    connect_phone_android: "Connect your Samsung Galaxy/Android with USB cable",
    connect_phone_iphone: "Connect your iPhone with USB cable",
    connect_phone_hint: "Unlock your phone and select \"File transfer\" if asked",
    connect_phone_search: "🔄 Search again",
    connect_phone_found: "Phone found! Opening photos...",
    connect_phone_scanning: "Phone found! Loading photos, please wait...",
    connect_phone_searching: "Searching for phone...",
    connect_phone_not_found: "No phone found. Make sure the USB cable is connected and the phone is unlocked.",
    phone_folders_title: "Select folder",
    phone_folders_hint: "Tap a folder to view photos",
    connect_phone_gvfs_hint: "Tip: Install gvfs-mtp if your phone does not appear.",
    print_done_title: "Thank you for your order!",
    print_done_subtitle: "Your photos are being printed. Please take them when ready.",
    confirm_clear_queue: "Confirm",
    wifi_qr_upload: "📶 WiFi / QR code",
    wifi_network_label: "Network",
    wifi_password_label: "Password",
    wifi_connect_then_scan: "1. Connect to WiFi above\n2. Scan the QR code with your camera",
    wifi_step_connect: "1. Connect to WiFi",
    wifi_step_upload: "2. Upload photos",
    mobile_cable_connect: "🔌 Connect with cable instead",
    select_all: "☑ Select all",
    deselect_all: "☐ Deselect all",
};

pub fn l(language: Language) -> &'static LangPack {
    match language {
        Language::Swedish => &SWEDISH,
        Language::English => &ENGLISH,
    }
}

pub fn copies_word(language: Language, count: u32) -> &'static str {
    let pack = l(language);
    if count == 1 {
        pack.copy_label
    } else {
        pack.copies_label
    }
}
